# Generated by Django 5.0.1 on 2024-04-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_cart_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="payment_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
