# Generated by Django 5.0.1 on 2024-05-01 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_alter_cart_payment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="payment_id",
        ),
    ]
