# Generated by Django 5.0.1 on 2024-05-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0019_remove_cart_payment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="picture",
        ),
    ]
