# Generated by Django 5.0.1 on 2024-05-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
